apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uz92y72pf-python
  janus-idp.io/tekton: uz92y72pf-python
  backstage.io/kubernetes-id: uz92y72pf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uz92y72pf-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
