apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uz92y72pf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uz92y72pf-python 
  name: uz92y72pf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uz92y72pf-python 
